### ISSUE TITLE
Error: exec: "/start.sh": stat /start.sh: no such file or directory: unknown

### ISSUE THREAD

**Issue by SWS-5007** [polkascan/harvester#13]
Hi, Greetings!
I deployed this `harvester` project on AWS Ubuntu.
Then, I run this command, `docker-compose up --build`, I am getting error below.
> 
> Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
> [+] Running 2/0
>  ⠿ Container shearscan_harvester-mysql-1           Running                                                                         0.0s
>  ⠿ Container shearscan_harvester-substrate-node-1  Running                                                                         0.0s
> Attaching to shearscan_harvester-harvester-1, shearscan_harvester-mysql-1, shearscan_harvester-substrate-node-1
> Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/start.sh": stat /start.sh: no such file or directory: unknown
> 

And here is my docker-compose.yml codebase.
```
version: '3.2'
services:
  harvester:
    build: .
    image: polkascan/harvester
    restart: unless-stopped
    entrypoint: /usr/src/start.sh
    ports:
      - '9620:9616'
    environment:
...
...
```

What is wrong?
**What should I do on AWS Ubuntu EC2 to solve this issue?**

**Comment by arjanz** [comment]
What is the reason you change the entrypoint from `/usr/src/start.sh` to `/start.sh`? If you didn't change the [workdir in the Dockerimage](https://github.com/polkascan/harvester/blob/7c4bef8b628e787bcfe6f3bbcef2855aa51c07d8/Dockerfile#L8) you should change it back.

**Comment by SWS-5007** [comment]
I changed again as you said but I am getting same error.

> Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/src/start.sh": permission denied: unknown

Here is changed `docker-compose.yml` codebase.

```
version: '3.2'
services:
  harvester:
    build: .
    image: polkascan/harvester
    restart: unless-stopped
    entrypoint: /usr/src/start.sh
```

What is wrong yet?
