### ISSUE TITLE
Error: (1064, "You have an error in your SQL syntax; ...)

### ISSUE THREAD

**Issue by SWS-5007** [polkascan/harvester#6]
Hi, When I run this `alembic upgrade head` command, I am getting this error below.

> ...
> ...
>   File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
>     err.raise_mysql_exception(self._data)
>   File "C:\Users\Home\AppData\Local\Programs\Python\Python310\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
>     raise errorclass(errno, errval)
> sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON) AS `value`\n                        LIMIT 1\n                    ) ON DUPLIC' at line 20")
> [SQL:
>             CREATE DEFINER=`root`@`%%` PROCEDURE `etl_range`(`block_start` INT(11), `block_end` INT(11), `update_status` INT(1))
>             BEGIN
>                 ### GLOBAL SETTINGS ###
>                 SET @block_start = `block_start`;
>                 SET @block_end = `block_end`;
>                 SET @update_status = `update_status`;
> 
>                 ### CALL OTHER STORED PROCEDURES ###
>                 CALL `etl_codec_block_timestamp`(`block_start`,`block_end`,`update_status`);
> 
>                 # CALL `stored_procedure_02`();
>                 # CALL `stored_procedure_03`();
> 
>                 ### UPDATE STATUS TABLE ###
>                 IF @update_status = 1 THEN
>                     INSERT INTO `harvester_status` (`key`,`description`,`value`)(
>                         SELECT
>                             'PROCESS_ETL' AS    `key`,
>                             'Max blocknumber of etl process' AS `description`,
>                             CAST(@block_end AS JSON) AS `value`
>                         LIMIT 1
>                     ) ON DUPLICATE KEY UPDATE
>                         `description` = VALUES(`description`),
>                         `value` = VALUES(`value`)
>                     ;
>                 END IF;
>             END
>                         ]
> (Background on this error at: https://sqlalche.me/e/14/f405)

Here is my docker-compose.yml file.
```
version: '3.2'

services:

  harvester:
    build: .
    image: polkascan/harvester
    restart: unless-stopped
    entrypoint: /usr/src/start.sh
    ports:
      - '9620:9616'
    environment:
      - DB_CONNECTION=mysql+pymysql://root@mysql:3306/polkascan?charset=utf8mb4
      - SUBSTRATE_RPC_URL=wss://sheartoken.com
#      - SUBSTRATE_RPC_URL=ws://host.docker.internal:9944
      - NODE_TYPE=archive
      - SUBSTRATE_SS58_FORMAT=42
    depends_on:
      - mysql
      - substrate-node

  substrate-node:
    image: arjanz/substrate-node-template:latest
    volumes:
      - 'substrate-node:/substrate'
    ports:
      - '9944:9944'
      - '9933:9933'
    command: --dev --ws-external --rpc-cors=all --rpc-external --rpc-methods=Unsafe --no-telemetry --no-prometheus --pruning=archive

  mysql:
    image: mysql:latest
    volumes:
      - 'mysql-data:/var/lib/mysql'
    ports:
      - '33061:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polkascan

volumes:
  substrate-node:
  mysql-data:

```
How to solve this error?
Please help me.
